version: '3.8'
services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - mysql  # 修正: mysql をリストとして指定
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # ルートパスワードを設定
      MYSQL_DATABASE: mydatabase         # 使用するデータベースを指定
      MYSQL_USER: user                   # ユーザー名
      MYSQL_PASSWORD: userpassword       # ユーザーパスワード
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    ports:
      - "3306:3306"  # ローカルでアクセスするためのポートを開放
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql  # MySQLのサービス名
      PMA_USER: user   # MySQLのユーザー名
      PMA_PASSWORD: userpassword  # MySQLのパスワード
    ports:
      - "8082:80"  # localhost:8082でphpMyAdminにアクセス (8081は php-app で使用済み)
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
